-- MySQL Script generated by MySQL Workbench -- 09/28/16 01:26:13 -- Model: New Model Version: 1.0 -- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
-- Schema circle_test
DROP SCHEMA IF EXISTS circle_test ;
-- Schema circle_test
CREATE SCHEMA IF NOT EXISTS circle_test DEFAULT CHARACTER SET utf8 ;
USE circle_test ;
-- Table circle_test.users
DROP TABLE IF EXISTS circle_test.users ;
CREATE TABLE IF NOT EXISTS circle_test.users(
	idusers INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(45) NOT NULL,
	bio VARCHAR(400) NULL,
	pass VARCHAR(40) NOT NULL,
    email VARCHAR(40) NOT NULL,
    privacy VARCHAR(40) NOT NULL,
	PRIMARY KEY (idusers),
	UNIQUE INDEX idusers_UNIQUE (idusers ASC),
	UNIQUE INDEX username_UNIQUE (username ASC)) ENGINE = InnoDB;
-- Table circle_test.routes
DROP TABLE IF EXISTS circle_test.routes ;
CREATE TABLE IF NOT EXISTS circle_test.routes (
	idroutes INT NOT NULL AUTO_INCREMENT,
	route VARCHAR(1000) NOT NULL,
	startPointLat VARCHAR(10) NOT NULL,
	startPointLon VARCHAR(10) NOT NULL,
	userid VARCHAR(45) NOT NULL,
	routeName VARCHAR(64) NOT NULL,
	PRIMARY KEY (idroutes),
	UNIQUE INDEX idroutes_UNIQUE (idroutes ASC)) ENGINE = InnoDB;
-- Table circle_test.comments
DROP TABLE IF EXISTS circle_test.comments ;
CREATE TABLE IF NOT EXISTS circle_test.comments (
	idcomments INT NOT NULL AUTO_INCREMENT,
	text VARCHAR(400) NOT NULL,
	userid VARCHAR(45) NOT NULL,
	timestamp TIMESTAMP,
	parent VARCHAR(45) NOT NULL,
	PRIMARY KEY (idcomments)) ENGINE = InnoDB;
	-- Table router.friends
	DROP TABLE IF EXISTS circle_test.friend ;
	CREATE TABLE IF NOT EXISTS circle_test.friend(
		user_id INT NOT NULL,
		friend_id INT NOT NULL,
		PRIMARY KEY (user_id, friend_id)) ENGINE = InnoDB;
	-- Table router.request
	DROP TABLE IF EXISTS circle_test.request ;
	CREATE TABLE IF NOT EXISTS circle_test.request(
		receiver_id INT NOT NULL,
		sender_id INT NOT NULL,
		PRIMARY KEY (receiver_id,sender_id)) ENGINE = InnoDB;
	-- Table router.share
	DROP TABLE IF EXISTS circle_test.shared;
	CREATE TABLE IF NOT EXISTS circle_test.shared(
		shared_id INT NOT NULL AUTO_INCREMENT,
		receiver_id INT NOT NULL,
		sender_id INT NOT NULL,
		route_id INT NOT NULL,
		PRIMARY KEY (shared_id)) ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
